name: Deploy MultiDocker
on:
  push:
    branches:
      - main 
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jeevannaik/complex-react-test -f Dockerfile.dev .
      - run: docker run -e CI=true jeevannaik/complex-react-test npm test

      - run: docker build -t jeevannaik/complex-react-client ./client
      - run: docker build -t jeevannaik/complex-react-nginx ./nginx
      - run: docker build -t jeevannaik/complex-react-server ./server
      - run: docker build -t jeevannaik/complex-react-worker ./worker

      - run: docker push jeevannaik/complex-react-client
      - run: docker push jeevannaik/complex-react-nginx
      - run: docker push jeevannaik/complex-react-server
      - run: docker push jeevannaik/complex-react-worker 
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'